version: "3.7"

services:
  postgres:
    container_name: go_postgres
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      TZ: "Etc/UTC"
    volumes:
      - postgres:/data/postgres
    networks:
      - ${NETWORK}

networks:
  go-network:
    driver: bridge
    name: ${NETWORK}

volumes:
  postgres:
